### ISSUE TITLE
About the response.txt

### ISSUE THREAD

**Issue by HarryG55** [ptrtonull-workshop/PianYuan#33]
All of the Beautifulsoup is save to the same document: response.txt.
Did this action will cause problems which we haven't find yet?

**Comment by WangTingZheng** [comment]
your means requirements.txt? this is the informtion of package which this project needs to install. includes package name and version number.

**Comment by WangTingZheng** [comment]
this is not only about beautufusoup. without   
it, other developer will have an error which is about "invalid import"

**Comment by HarryG55** [comment]
No. is the document which is response for save the data.

ex.
def get_list(url):
    number = 1
    response = requests.get(url)
    soup = BeautifulSoup(**response.text**, 'html.parser')
    items = soup.find_all(name='div', attrs={'class': 'col-sm-3 col-md-3 col-xs-4 col-lg-2 nopl'})

**Comment by WangTingZheng** [comment]
no,  they are in different functions, after the function run finished, the `response.txt` will be deleted and the new one will be updated according to new functions' settings.
