### ISSUE TITLE
大氵逼来了

### ISSUE THREAD

**Issue by CaesinEachonson** [ptrtonull-workshop/PianYuan#46]
我的水量，超乎你的想象

**Comment by WangTingZheng** [comment]
do your job, No BB

**Comment by CaesinEachonson** [comment]
捯饬环境呢。
注意，请确保./vscode/settings.json里的路径与你电脑内的python路径一致,本项目采用的是python 3.7.4
这个没整好，要不你过来帮我分析一下

**Comment by WangTingZheng** [comment]
> 
> 
> 捯饬环境呢。
> 注意，请确保./vscode/settings.json里的路径与你电脑内的python路径一致,本项目采用的是python 3.7.4
> 这个没整好，要不你过来帮我分析一下

你用的pycharm还是vscode？

**Comment by CaesinEachonson** [comment]
> > 捯饬环境呢。
> > 注意，请确保./vscode/settings.json里的路径与你电脑内的python路径一致,本项目采用的是python 3.7.4
> > 这个没整好，要不你过来帮我分析一下
> 
> 你用的pycharm还是vscode？

vscode。操作系统环境变量设的没问题，vscode里我得cd到python路径才能开。
