### ISSUE TITLE
translate Chinese to English

### ISSUE THREAD

**Issue by WangTingZheng** [ptrtonull-workshop/PianYuan#63]
- update `README-EN.md`
@HarryG55

**Comment by HarryG55** [comment]
the document's mean is OK. but it have so many grammer and expression problem which need to modify. Therefore I will change some of the Chinese README to make it more readable and fluent.

**Comment by WangTingZheng** [comment]
> the document's mean is OK. but it have so many grammer and expression problem which need to modify. Therefore I will change some of the Chinese README to make it more readable and fluent.

if you want me to fix it, please tell me some specific suggestions, I will fix it. (if i can find some irrational bug, I can fix it on my own before I update it), if you want to fix on your own, You can ask any question about README if you don't not make sure what do i mean.

**Comment by HarryG55** [comment]
DONE.
@WangTingZheng
